### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by mva1985** [phorward/rapidbatch#1]
any chance of getting a windows build while your development is ongoing?

**Comment by phorward** [comment]
Hi there,

I've performed the steps described in https://github.com/phorward/rapidbatch#building within an MSYS2 environment on Windows 10 and successfully got rb6.exe (after fixing a little bug in getcharat.c and the Makefile, see diff). diff+exe are in [rb6.zip](https://github.com/phorward/rapidbatch/files/2749441/rb6.zip).

![capture](https://user-images.githubusercontent.com/16870072/51031652-87913500-159d-11e9-8e9e-8bbaaa4ea157.PNG)

For now, it is only a console program because it implements the compiler/vm interpreter right now without any Windows-related features. Because I'm no longer in development on this project there won't be any huger developments ongoing, except somebody else wants to...
